package com.wildeats.onlinecanteen.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.wildeats.onlinecanteen.entity.OrderItemEntity;

import java.util.List;

@Repository
public interface OrderItemRepository extends JpaRepository<OrderItemEntity, Long> {
    /**
     * Find all order items for a specific order
     * 
     * @param orderId The ID of the order
     * @return List of order items for the order
     */
    List<OrderItemEntity> findByOrderOrderId(Long orderId);

    /**
     * Find all order items for a specific menu item
     * 
     * @param menuItemId The ID of the menu item
     * @return List of order items for the menu item
     */
    List<OrderItemEntity> findByMenuItemItemId(Long menuItemId);

    /**
     * Count total quantity sold for a specific menu item
     * 
     * @param menuItemId The ID of the menu item
     * @return Total quantity sold
     */
    @Query("SELECT COALESCE(SUM(oi.quantity), 0) FROM OrderItemEntity oi WHERE oi.menuItem.itemId = :menuItemId")
    Integer countTotalQuantitySoldForMenuItem(@Param("menuItemId") Long menuItemId);

    /**
     * Find top selling items for a shop
     * 
     * @param shopId The ID of the shop
     * @param limit  The maximum number of items to return
     * @return List of order items representing top sellers
     */
    @Query(value = "SELECT oi.* FROM order_item oi " +
            "JOIN orders o ON oi.order_id = o.order_id " +
            "WHERE o.shop_id = :shopId AND o.status = 'COMPLETED' " +
            "GROUP BY oi.item_id " +
            "ORDER BY SUM(oi.quantity) DESC " +
            "LIMIT :limit", nativeQuery = true)
    List<OrderItemEntity> findTopSellingItemsForShop(@Param("shopId") Long shopId, @Param("limit") int limit);

    /**
     * Calculate total revenue for a specific menu item
     * 
     * @param menuItemId The ID of the menu item
     * @return Total revenue generated by the menu item
     */
    @Query("SELECT COALESCE(SUM(oi.quantity * oi.priceAtPurchase), 0) FROM OrderItemEntity oi " +
            "JOIN oi.order o WHERE oi.menuItem.itemId = :menuItemId AND o.status = 'COMPLETED'")
    Double calculateRevenueForMenuItem(@Param("menuItemId") Long menuItemId);

    /**
     * Delete all order items for a specific order
     * 
     * @param orderId The ID of the order
     */
    void deleteByOrderOrderId(Long orderId);
}